sonar.projectKey=abelnhm_todotecnofertas-frontend
sonar.organization=abelnhm


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=todotecnofertas-frontend
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.*, **/*.spec.*, src/main.tsx, src/vite-env.d.ts, src/config.ts, src/services/local.storage.ts, src/store/store.ts, src/services/cloudinary.ts
